### ISSUE TITLE
Exceptions / Tests

### ISSUE THREAD

**Issue by Unitech** [keymetrics/kmjs-core#10]
https://gist.github.com/Unitech/eff4887e57237ecc5a4aa90c92944798

Created free account, copy / pasted an admin token, not managed to get public key https://travis-ci.org/search/keymetrics.js

```bash
$ npm test
```

**Comment by vmarchaud** [comment]
Done via https://github.com/keymetrics/kmjs-core/commit/82aefc04d943c4f326f0c7b4a52933d98fca779e
