### ISSUE TITLE
Add data mutation at class initialization

### ISSUE THREAD

**Issue by Unitech** [keymetrics/kmjs-core#11]
Add data mutation at keymetrics.js class initialization.
Allow to specify the way data received should be formated (km-front like etc)

**Comment by vmarchaud** [comment]
The client is only intended to be have a low level interaction with the API, it should be stateless so i don't think it should have any data transformer and even less having data added as property of exported namespaces (for example `km.bucket.apps[name]` or `km.bucket.servers[name]`).
