### ISSUE TITLE
Can't run client side library

### ISSUE THREAD

**Issue by Unitech** [keymetrics/kmjs-core#17]
After having run `npm run build` + `npm run dist` and included the minified file into a html page, I get the following error when instantiating the Keymetrics class:

```
keymetrics.es5.min.js:1 Uncaught TypeError: this._queueWorker.unref is not a function
    at new e (keymetrics.es5.min.js:1)
    at new t (keymetrics.es5.min.js:1)
    at main.js:3
```

**Comment by nayrrod** [comment]
Same for me. Strangely this only happens on staging.

**Comment by vmarchaud** [comment]
Fixed
