### ISSUE TITLE
meta: add version of client in user agent

### ISSUE THREAD

**Issue by vmarchaud** [keymetrics/kmjs-core#55]

**Comment by BenoitZugmeyer** [comment]
On Chrome (and apparently Safari), you can't set the `User-Agent`. This won't break the XHR, just printing an error in the devtools console.

Reduced test-case:
```js
var xhr = new XMLHttpRequest()
xhr.open('GET', '/')
xhr.setRequestHeader('User-Agent', 'foo'); xhr.send() }
```

Proposal: add a `X-JS-API-Version` instead?
